from utils.hitbox import Hitbox


class Widget:
    def __init__(self, menu):
        self.menu = menu
        self.hitbox: Hitbox

    def update(self) -> None: ...
    def draw(self) -> None: ...
    def is_focused(self) -> bool: ...
    def on_click(self) -> None: ...
    def on_focus(self) -> None: ...
    def on_unfocus(self) -> None: ...
